<?php

function leaguerunner_help($section) {
  $output = null;
  switch($section) {
    case 'admin/system/modules#description':
      $output = t("Lets users log in using a Leaguerunner ID.");
	  break;
	case 'user/help#leaguerunner':
	  $output = t("If you have an account on OCUA's Leaguerunner system (<a href=\"http://www.ocua.ca/leaguerunner/\">http://www.ocua.ca/leaguerunner/</a>), you may log in using your Leaguerunner username.");
	  break;
  } 
  return $output;
}

function leaguerunner_settings() {
  $output = form_textfield("Leaguerunner database name", "leaguerunner_dbname", variable_get("leaguerunner_dbname", "leaguerunner"), 55, 128, "The name of your Leaguerunner database.  Must be accessible by the database user configured for Drupal.");

  return $output;
}

/**
 * Here, we validate the user in the Leaguerunner db.
 */
function leaguerunner_auth($username, $password, $userServer) {

  if($userServer !== 'ocua') {
    return 0;
  }

  $lrUser = _leaguerunner_user_load( array('username' => $username, 'password' => $password));

  if($lrUser) {
    _leaguerunner_set_session( $lrUser, session_id() );
    return array(
	  'mail' => $lrUser->email,
	  'name' => "$lrUser->firstname $lrUser->lastname",
	);
  } 
  return 0;
}

function leaguerunner_remote_fields() {
	return array ( 'mail', 'name', 'pass1', 'pass2');
}

function leaguerunner_user ($type, $edit, $user) {

  $result = user_get_authmaps($user->init);
  if(!$result['leaguerunner']) {
    return '';
  }

  switch($type) {
    case "view_private":
    case "edit_form":
	  return form_item(t("Other Information"), "The remainder of your private information is stored in <a href='/leaguerunner'>Leaguerunner</a>.");
    case "edit_validate":
	  foreach(leaguerunner_remote_fields() as $field) {
	    if(in_array($field, array_keys($edit))) {
			$error .= "Cannot edit $field on a leaguerunner user<br />";
		}
	  }
	  return $error ? $error : $edit;
  }
}

/**
 * Destroy a Leaguerunner session.  Should get called by sess_destroy()
 * in user.module.
 */
function leaguerunner_destroy( $user, $key ) {
  global $db_resource, $db_url;
  
  $parsedUrl = parse_url($db_url);
  $db_name = substr($parsedUrl['path'],1);
  mysql_select_db("leaguerunner", $db_resource);

  /* Nuke session cookie for Leaguerunner */  
  db_query("UPDATE person SET session_cookie = NULL WHERE session_cookie = '%s'", $key);

  mysql_select_db($db_name, $db_resource);
}

function _leaguerunner_set_session ( $lrUser, $sess ) {
  global $db_resource, $db_url;
  $parsedUrl = parse_url($db_url);
  $db_name = substr($parsedUrl['path'],1);
  mysql_select_db("leaguerunner", $db_resource);

  /* Also set session cookie for Leaguerunner */  
  db_query("UPDATE person SET session_cookie = '%s', last_login = NOW(), client_ip = '%s' WHERE user_id = %d", $sess, $_SERVER['REMOTE_ADDR'], $lrUser->user_id);

  mysql_select_db($db_name, $db_resource);
}

function _leaguerunner_user_load ($array = array() ) {
  global $db_resource, $db_url;
  $parsedUrl = parse_url($db_url);
  $db_name = substr($parsedUrl['path'],1);
  mysql_select_db("leaguerunner", $db_resource);

  $query = "";

  foreach ($array as $key => $value) {
    if ($key == "password") {
      $query .= "u.$key = '". md5($value) ."' AND ";
    }
    else {
      $query .= "u.$key = '". check_query($value) ."' AND ";
    }
  }
  $result = db_query_range("SELECT u.* FROM person u WHERE $query status = 'active'", 0, 1);

  $user = db_fetch_object($result);
  mysql_select_db($db_name, $db_resource);
  return $user;
}

function _leaguerunner_next_games (  ) {
  global $db_resource, $db_url;
  $player = _leaguerunner_user_load( array('session_cookie' => session_id()));
  
  $parsedUrl = parse_url($db_url);
  $db_name = substr($parsedUrl['path'],1);
  
  mysql_select_db("leaguerunner", $db_resource);


  $result = db_query("select s.game_id, UNIX_TIMESTAMP(s.date_played) AS date, IF(s.home_team = t.team_id,home.name,away.name) AS myteam, IF(s.home_team = t.team_id,away.name,home.name) AS opponent from schedule s, teamroster t INNER JOIN team home ON (home.team_id = s.home_team) INNER JOIN team away ON (away.team_id = s.away_team) WHERE ((s.home_team = t.team_id OR s.away_team = t.team_id) AND t.player_id = %d) AND s.date_played > NOW()  ORDER BY date_played asc LIMIT 3", $player->user_id);

  $games = array();
  while($item = db_fetch_object($result)) {
    $games[] = $item;
  }
  mysql_select_db($db_name, $db_resource);
  return $games;
}

function leaguerunner_count_games_for_date ( $year, $month, $day )
{
  global $db_resource, $db_url;
  $parsedUrl = parse_url($db_url);
  $db_name = substr($parsedUrl['path'],1);
  mysql_select_db("leaguerunner", $db_resource);
  $result = db_query("select COUNT(*) from schedule WHERE YEAR(date_played) = %d AND DAYOFYEAR(date_played) = DAYOFYEAR('%d-%d-%d')", $year, $year, $month, $day);
  $numGames = db_result($result);
  mysql_select_db($db_name, $db_resource);
  return $numGames;
}

function leaguerunner_info($field = 0) {
  $info["name"] = "leaguerunner";

  if ($field) {
    return $info[$field];
  }
  else {
    return $info;
  }
}

/**
 * Here we need to create our own user info block that doesn't
 * present the ability to edit settings for Leaguerunner-authenticated users.
 * Also creates a 'My Games' block for upcoming games.
 */
function leaguerunner_block($op = "list", $delta = 0) {
  global $user;

  $edit = $_POST["edit"];

  if ($op == "list") {
     $blocks[0]["info"] = t("User Login (Leaguerunner Custom)");
     $blocks[1]["info"] = t("User information (Leaguerunner Custom)");
     $blocks[2]["info"] = t("Leaguerunner game data");
     return $blocks;
  }
  else {
    switch ($delta) {
      case 0:
        if (!$user->uid) {
          /*
          ** For usability's sake, avoid showing two login forms on one
          ** page.
          */

          if (arg(0) == "user" && arg(1) != "view") {
            return;
          }

          $output = "<div class=\"user-login-block\">\n";

          /*
          ** Save the referer.  We record where the user came from such
          ** that we/ can redirect him after having completed the login
          ** form.
          */

          if (empty($edit)) {
            $edit["destination"] = url($_GET["q"]);
          }
          // NOTE: special care needs to be taken because on pages with forms, such as node and comment submission pages, the $edit variable might already be set.

          $form = form_hidden("destination", $edit["destination"]);
          $form .= form_textfield(t("Username"), "name", $edit["name"], 15, 64);
          $form .= form_password(t("Password"), "pass", $pass, 15, 64);

          if (variable_get("user_remember", 0) == 0) {
            $form .= form_checkbox(t("Remember me"), "remember_me", 1, 0, 0);
          }
          elseif (variable_get("user_remember", 1) == 1) {
            $form .= form_hidden("remember_me", 1);
          }

          $form .= form_submit(t("Log in"));

          $output .= form($form, "post", url("user/login"));

          $output .= "</div>\n";

          $block["subject"] = t("User login");
          $block["content"] = $output;
          return $block;
        }
        break;
      case 1:
	      break;
      case 2:
        if ($user->uid) {
	      $authmap = user_get_authmaps($user->init);
	      if($authmap['leaguerunner'] ) {
	        $lrUser = _leaguerunner_user_load( array( 'session_cookie' => session_id()));
            $output = "<div class=\"next-games\">\n";
            $games = _leaguerunner_next_games();
            if(count($games)) {
              foreach ($games as $game) {
                $minutesleft = ( $game->date - time()) / 60;
                if ( $minutesleft < 90 )
                  $timeleft = round($minutesleft) . " " . t('minutes');
                else if ( $minutesleft < (2*24*60) )
                  $timeleft = round($minutesleft/60) . " " . t('hours');
                else
                  $timeleft = round($minutesleft/(24*60)) . " " . t('days');

  	            $items[] = "<a href=\"/leaguerunner/game/view/$game->game_id\">$game->myteam vs. $game->opponent</a> ($timeleft)";
              }

              $output .= theme("theme_item_list", $items);
            } else {
              $output .= "No games scheduled";
            }
            $output .= "</div>\n";

		    $block["subject"] = "My Games";
			$block["content"] = $output;
			return $block;
          }
        }
    }
  }
}
?>
