alter table person add status enum('new','inactive','active','locked') after class;
update person set status = 'new' where class= 'new';
update person set status = 'inactive' where class= 'inactive';
update person set status = 'active' where class= 'active';
update person set status = 'locked' where class= 'locked';
update person set status = 'active' where class= 'volunteer';
update person set status = 'active' where class= 'administrator';
alter table person change class class enum('new','inactive','active','locked','volunteer','administrator','player') DEFAULT 'player';
update person set class = 'player' where class != 'administrator' AND class != 'volunteer';
alter table person change class class enum('volunteer','administrator','player') DEFAULT 'player'; 
